name: titactoe_api
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  broadcast_bloc: ^0.1.0-dev.2
  dart_frog: ^1.0.0
  dart_frog_web_socket: ^1.0.0
  dotenv: ^4.2.0
  equatable: ^2.0.5
  supabase: ^2.1.2
  web_socket_channel: ^2.4.5

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
